name: seventy_five_hard
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  http: ^1.0.0
  provider: ^6.0.5
  supabase_flutter: ^1.10.1
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  percent_indicator: ^4.2.3
  flutter_local_notifications: ^14.1.1
  timezone: ^0.9.2
  android_alarm_manager_plus: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  background_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
